//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineCard()
        {
            this.Transfer = new HashSet<Transfer>();
        }
    
        public int id { get; set; }
        public string FIO { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string PreliminaryDiagnosis { get; set; }
        public int EntryMethodId { get; set; }
        public System.DateTime RecieptDate { get; set; }
        public Nullable<int> DescriptionsId { get; set; }
        public Nullable<int> EndOfThreatmentId { get; set; }
    
        public virtual DescriptionPatient DescriptionPatient { get; set; }
        public virtual EndOfThreatment EndOfThreatment { get; set; }
        public virtual EntryMethod EntryMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfer { get; set; }
    }
}
