//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProject.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicalHospitalRecordsEntities1 : DbContext
    {
        private static Entities.ClinicalHospitalRecordsEntities1 _context = new ClinicalHospitalRecordsEntities1();
        public ClinicalHospitalRecordsEntities1()
            : base("name=ClinicalHospitalRecordsEntities1")
        {
        }
    
        /// <summary>
        /// Создание контекста Базы Данных.
        /// </summary>
        /// <returns> Контекст Базы Данных. </returns>
        public static Entities.ClinicalHospitalRecordsEntities1 GetContext()
        {
            if (_context == null)
                _context = new Entities.ClinicalHospitalRecordsEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DescriptionPatient> DescriptionPatient { get; set; }
        public virtual DbSet<EndOfThreatment> EndOfThreatment { get; set; }
        public virtual DbSet<EntryMethod> EntryMethod { get; set; }
        public virtual DbSet<MedicineCard> MedicineCard { get; set; }
        public virtual DbSet<ReasonForDischarge> ReasonForDischarge { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
    }
}
