//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProject.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int id { get; set; }
        public int MedicineCardId { get; set; }
        public System.DateTime DateOdTransfer { get; set; }
        public string ChamberPhone { get; set; }
        public int NewChamber { get; set; }
    
        public virtual MedicineCard MedicineCard { get; set; }
    }
}
